<?php

namespace App\DataFixtures;

use App\Entity\Category;
use App\Entity\Tag;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class CategoryFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        foreach ($this->getListOfCategories() as $categoryName) {
            $category = new Category();
            $category->setName($categoryName);
            $manager->persist($category);
        }

        $manager->flush();
    }


    protected function getListOfCategories()
    {
        return [
            '#SRFglobal',
            '+3°',
            '00_Test',
            '1 gegen 100',
            '1. Staffel',
            '10 Jahre Masoala-Halle ',
            '10 Jahre Youtube',
            '10 vor 10',
            '100 Franken-Autobahnvignette',
            '100 Jahre Kurt Früh',
            '100 Jahre Nationalpark',
            '100 onns Tista Murk',
            '100 Sekunden mit...',
            '100 Sekunden Wissen',
            '10v10-Wahlserie',
            '10vor10',
            '11 x ehrlich',
            '1945',
            '1989 – die Wende',
            '1:12-Initiative',
            '2 Familien, 1 Schweiz',
            '2 x Nadal',
            '2. Gotthard-Röhre',
            '2. Staffel',
            '2010',
            '2011',
            '2012',
            '2013',
            '2014',
            '2015 - SKJF a Mustér',
            '2015',
            '2016',
            '2017 - Falera conta',
            '2017 - Festival da jazz',
            '2017 - SKJF a Lugano',
            '2017',
            '2018 - Festival da jazz',
            '2018 - Rezia Cantat',
            '2018',
            '2019 – Festival da jazz',
            '2019',
            '25 Jahre Kontext',
            '26minutes',
            '2x Weihnachten',
            '3 vo 5',
            '30 Jahre Regionaljournal',
            '30 Jahre SRF 3',
            '35 onns producziun da musica',
            '360°-Ansichten',
            '4 in einem Boot',
            '4. Staffel',
            '40 Jahre Kassensturz',
            '4X4',
            '5 Menschen, 5 Diäten',
            '500 onns refurmaziun',
            '52 beste Bücher',
            '6 Fragen an ...',
            '6 Thesen zum Bund fürs Leben',
            '70 Jahre «Echo der Zeit»',
            '75 Jahre Lucerne Festival ',
            '8-Millionen Schweiz',
            '8x15',
            '8x15.',
            'Ägyptische Revolution',
            'Änderung RTVG',
            'Ärzte VS Internet',
            'Über das Hölloch',
            'Über Stock und Stein',
            'Über uns',
            'Übersicht',
            'Überwachung Sozialversicherte',
            'A Hard Days Night',
            'A point',
            '«Als Grufti id Stifti»',
            '«Berliner Notizen»',
            '«Bio vs. Konventionell»',
            '«Dä Kafisatz»',
            '«Der fliegende Holländer»',
            '«Die chline Böse»',
            '«Die Maintöchter»',
            '«Einstein» entdeckt',
            '«Einstein»-Spezial: Kleider',
            '«Espresso Aha!»',
            '«Espresso bi dä Tüftler»',
            '«Espresso goht fremd»',
            '«Espresso H2Ohhh!»',
            '«Espresso Retro»',
            '«Espresso Ristretto»',
            '«Espresso usser Huus» ',
            '«Espresso» nachtaktiv',
            '«Espresso»-Glossen',
            '«Espresso»-Interna',
            '«Ganz tierisch»',
            '«glanz & gloria feiert mit»',
            '«Kassensturz undercover»',
            '«Kassensturz»-Interna',
            '«Mein Lehrer aus dem Internet»',
            '«Mortori a…»',
            '«Netzwerke der Zukunft»',
            '«No Billag»-Initiative',
            '«Puls»-Chats',
            '«Rechtsmitteli»',
            '«Schredder»',
            '«Trick 77»',
            '«Wer wars?»',
            '«Who Is Who» bei Wagner',
            'A1 – Die Raststätte',
            'Aargau Solothurn',
            'ABC SRF 3',
            'ABC-DGST',
            'About',
            'Abschiede 2014',
            'Abschiede 2016',
            'Abschiede 2017',
            'Abschiede 2018',
            'Abschiede 2019',
            'Abschiede',
            'Abstimmung 27. September 2020',
            'Abstimmung 29. November 2020',
            'Abstimmung GR',
            'Abstimmung Luzern',
            'Abstimmung Schaffhausen',
            'Abstimmung St. Gallen',
            'Abstimmung vom 27.September 21',
            'Abstimmung Zürich',
            'Abstimmungen  AG',
            'Abstimmungen  BL',
            'Abstimmungen 12. Februar 2017',
            'Abstimmungen 13. Juni 2021',
            'Abstimmungen 14.6.2015',
            'Abstimmungen 18.5.2014',
            'Abstimmungen 19. Mai 2019',
            'Abstimmungen 19.5.2019',
            'Abstimmungen 21. Mai 2017',
            'Abstimmungen 22.09.2013',
            'Abstimmungen 24. September',
            'Abstimmungen 25. November 2020',
            'Abstimmungen 25.09.2016',
            'Abstimmungen 25.11.2018',
            'Abstimmungen 27. September',
            'Abstimmungen 27.11.2016',
            'Abstimmungen 3.3.2013',
            'Abstimmungen 30.11.2014',
            'Abstimmungen 4. März 2018',
            'Abstimmungen 7. März 2021',
            'Abstimmungen 8.3.2015',
            'Abstimmungen 9. Februar 2020',
            'Abstimmungen 9.2.2014',
            'Abstimmungen 9.6.2013',
            'Abstimmungen Aarau',
            'Abstimmungen AG',
            'Abstimmungen Altstätten',
            'Abstimmungen AR',
            'Abstimmungen Arosa',
            'Abstimmungen Au-Heerbrugg',
            'Abstimmungen Baar und Zug',
            'Abstimmungen Baden',
            'Abstimmungen Baselland',
            'Abstimmungen BE',
            'Abstimmungen Bern',
            'Abstimmungen Biel',
            'Abstimmungen BL',
            'Abstimmungen BS',
            'Abstimmungen Chur',
            'Abstimmungen Davos',
            'Abstimmungen Emmen',
            'Abstimmungen Entlebuch',
            'Abstimmungen FR',
            'Abstimmungen Frauenfeld',
            'Abstimmungen Freiburg',
            'Abstimmungen GE',
            'Abstimmungen Genf',
            'Abstimmungen Goms',
            'Abstimmungen Gossau',
            'Abstimmungen GR',
            'Abstimmungen JU',
            'Abstimmungen Köniz',
            'Abstimmungen LU',
            'Abstimmungen Luzern',
            'Abstimmungen Montana',
            'Abstimmungen Moutier',
            'Abstimmungen Murten',
            'Abstimmungen NE',
            'Abstimmungen Neuhausen',
            'Abstimmungen NW',
            'Abstimmungen Oberrubrik',
            'Abstimmungen OW',
            'Abstimmungen Parc Adula',
            'Abstimmungen Rorschacherberg',
            'Abstimmungen Salez',
            'Abstimmungen Schaffhausen',
            'Abstimmungen SG',
            'Abstimmungen SH',
            'Abstimmungen SO',
            'Abstimmungen Solothurn',
            'Abstimmungen Spital Affoltern',
            'Abstimmungen St. Gallen ',
            'Abstimmungen St. Gallen',
            'Abstimmungen St. Moritz',
            'Abstimmungen SZ',
            'Abstimmungen Test',
            'Abstimmungen TG',
            'Abstimmungen Thun',
            'Abstimmungen TI',
            'Abstimmungen und Wahlen AR',
            'Abstimmungen und Wahlen BL',
            'Abstimmungen und Wahlen Chur',
            'Abstimmungen und Wahlen Zürich',
            'Abstimmungen UR',
            'Abstimmungen VD',
            'Abstimmungen vom 10. Juni 2018',
            'Abstimmungen vom 10.2.2019',
            'Abstimmungen vom 23.09.2018',
            'Abstimmungen vom 24.11.2013',
            'Abstimmungen vom 28.2.2016',
            'Abstimmungen vom 28.9.2014',
            'Abstimmungen vom 5.6.2016',
            'Abstimmungen VS',
            'Abstimmungen Waadt',
            'Abstimmungen Winterthur',
            'Abstimmungen Zürich',
            'Abstimmungen ZG',
            'Abstimmungen ZH',
            'Abstimmungen Zug',
            'Abstimmungen',
            'Abstimungen AR',
            'Abtreibungsfinanzierung',
            'Abzocker-Initiative',
            'Accents 2017',
            'Accents',
            'Actualitad musica',
            'Actualitad',
            'Acziuns RTR',
            'Adventsgeschichte',
            'Adventskalender 2013',
            'Adventskalender SRF Musikwelle',
            'Adventskalender',
            'Afrika – ungezähmter Kontinent',
            'Afrika–jenseits der Klischees',
            'Agglo',
            'AHV-Initiative',
            'AHV-Steuervorlage',
            'Aktuell',
            'Aktuelle Themen',
            'Album-Check',
            'Alle Cover-Songs',
            'Alle Sendungen',
            'Alle',
            'Allegra Rumantschs',
            'Allegra Vorarlberg…',
            'Allegra',
            'Alles was Recht ist!',
            'Allgemein',
            'Allgemeine Infos',
            'Allgemeines',
            'Alltag & Umwelt',
            'Alp Q&A',
            'Alpabfahrt Urnäsch',
            'Alpen und Älpler',
            'Alpenreise: Gemeindespiel',
            'Alpenreise: Höhenfieber',
            'Alpenreise: Postkartenaktion',
            'Alpenreise: Tagebuch',
            'Alpsommer',
            'Alternativmedizin',
            'Alzheimer hautnah',
            'Am Puls der Wirtschaft',
            'American Football',
            'Ampère',
            'Animalopus',
            'Animals e natira Surmiran',
            'Animals e natira Sursilvan',
            'Anklagepunkt 1',
            'Anklagepunkt 2',
            'Anklagepunkt 3',
            'Anlaufstellen',
            'Anlklagepunkt 3',
            'Anna erfüllt Wünsche',
            'Anno 1914 - Die Fabrik',
            'Anno 1914',
            'Anno Puls',
            'Ansichten: Schweizer Literatur',
            'Anti-Diskriminierungs-Gesetz',
            'Arbeit',
            'Arbeitgeber SRF',
            'Arbeitsgesetz',
            'Arbeitsrecht',
            'Archiv',
            'Archiv-Perlen',
            'Archivperlen',
            'Are 2019',
            'Arena Spezial',
            'Arena vor Ort',
            'Arena',
            'Arena/Reporter',
            'Arktis',
            'Arosa Humorfestival',
            'Artg musical',
            'Artikel',
            'As Time Goes By',
            'Asylgesetz',
            'Atlas',
            'Atom',
            'Atomausstiegs-Initiative',
            'ATP-Tour',
            'Audios und Videos ',
            'Audios und Videos',
            'Audios',
            'Auf den Spuren eures Namens',
            'Auf und davon',
            'Aufgedeckt',
            'Aufhebung der Wehrpflicht',
            'Aufsteller der Woche',
            'Aufsteller',
            'Aura',
            'Auszeichnungen',
            'Autobahn A1',
            'Autobahnvignette',
            'Automated Testing',
            'Axeit agleit: Stil mit Schube',
            'Bälpmoos – New York – Tokio',
            'Bäsefrässer',
            'Bücher / Spiele',
            'Bücher',
            'Bühne',
            'Backen',
            'Backstage',
            'Badekulturen',
            'Badewetter',
            'Badminton',
            'Ballape regiunal',
            'Ballape scolas medias 2017',
            'Baratta chor',
            'Baratta-Chor',
            'Barock – mon amour',
            'Barock: Beller erklärt',
            'Barock: Der Strassencheck',
            'Barock: Die Hörspiel-Soap',
            'Barock: Die Sendungen',
            'Barrierefreiheit',
            'Baseball',
            'Basel Baselland',
            'Basel Stadt',
            'Basel Tattoo',
            'Basketball',
            'Basler Fasnacht',
            'Basler-Fasnacht',
            'Battaporta',
            'Battle Mansion',
            'Beachsoccer',
            'Beachvolleyball',
            'Begrenzungsiniative',
            'Begrenzungsinitiative',
            'Beinverlängerung',
            'Beispiel-Artikel (keine Tests)',
            'Beiträge Flughafen Zürich',
            'Beiträge Zürich-West',
            'Beiträge zur Alpabfahrt',
            'Bel e bombastic',
            'Benissimo',
            'Beratungsstellen',
            'Bergretter',
            'Bern Freiburg Wallis',
            'Berner Oberländer Skiwoche',
            'Berufsfachschule',
            'Berufsporträts',
            'Berufswelt',
            'Besessen vom Essen',
            'Besser als Büsser',
            'Besser Macher',
            'Besser schlafen',
            'Best of - SRF 4 News',
            'Besteigung Mönch',
            'Bestseller Plattenteller',
            'Besucherführungen',
            'Bezirk Einsiedeln',
            'Bi dir',
            'Biathlon',
            'Big Dada',
            'Big Data: Das grosse Vermessen',
            'BigDada-TV-Sendungen',
            'BigDada: «Dada-Data»',
            'BigDada: Artikel',
            'BigDada: Dada-Data',
            'BigDada: Radio-Sendungen',
            'Bilantscha da program',
            'Bildergalerien',
            'Bipeds',
            'Biros',
            'Black Music Special',
            'Blick ins Feuilleton',
            'Blickpunkt Religion',
            'Blickwechsel',
            'Blitzlicht Schweiz',
            'Blues Special',
            'BMI-Rechner',
            'Boa tarde Rio',
            'Bob de Boumaa',
            'Bob',
            'Bom dia Rio',
            'Bonaparte Radio Show',
            'Bonjour e bonsoir la France',
            'Bonsoir la France',
            'Bounce Hip Hop Playlist',
            'Bounce Hip Hop',
            'Bounce One Man One Mix',
            'Bounce',
            'Boxen',
            'Brasilien',
            'Brasilien: Sendungen',
            'Brauchtum',
            'Bregenzer Festspiele',
            'Buch-Tipp',
            'Buch-Tipps',
            'Buchtipp zur Sendung',
            'Buchzeichen',
            'Bundeshaus live',
            'Bundeshaus und Parlament',
            'Bundesratswahlen 2015',
            'Bundesratswahlen',
            'Burning Mountain Festival',
            'Burnout & Stress',
            'Bytes/Pieces',
            'Campiunadi ball scolas medias',
            'Campiunadis mundials 2015',
            'Campiunadis mundials',
            'Cannes 2013',
            'Cannes 2014',
            'CH Beats',
            'CH Charts',
            'CH-Musik',
            'CH-Special',
            'Chadaina da Fortuna',
            'Challenge League',
            'Champions Hockey League',
            'Champions League',
            'Chant au tour',
            'Chantun',
            'Chanzuns',
            'Chapella Open Air',
            'Charts',
            'Chasa',
            'Chats',
            'Chatscha',
            'Cherchez la femme',
            'Chlini Prinzässin',
            'Chronik und Archiv',
            'CINEMAsuisse - Special',
            'CINEMAsuisse 2012',
            'Clip und Klar!',
            'Club',
            'Co e cum',
            'CO2-Gesetz',
            'Cocktail',
            'CollavuraturAs',
            'Comedians',
            'Comedy aus dem Labor',
            'Comedy',
            'Comedy-Frühling',
            'Community',
            'Computer im Beruf',
            'Concertino',
            'Concerto',
            'Confederations Cup',
            'Conference League',
            'Contact',
            'Corin Curschellas',
            'Corona',
            'Coronavirus',
            'Corrigenda',
            'Cortina 2021',
            'Country Special',
            'Cover Me - Special',
            'Cover me',
            'Covermania',
            'Covid-19',
            'Covid-19-Gesetz',
            'Croc SA',
            'Cultura',
            'Cuntrasts',
            'Cup',
            'Curling',
            'Cuschinar regiunal e stagiunal',
            'Custs d\'emissiun',
            'Custs',
            'Cypher',
            'Da lunsch davent',
            'Da num e da pum',
            'Dahinden - Anno 1914',
            'Dahinden - Bitte mitnehmen!',
            'Dahinden am Berg',
            'Dahinden am Gotthard',
            'Dahinden vor 500 Jahren',
            'Dal lontan el Grischun',
            'Danis-Tavanasa vs. Trun/Rabius',
            'Darf ich bitten?',
            'Darf man das?',
            'Darsteller & Figuren',
            'Darsteller und Figuren',
            'Das digitale Ich',
            'Das Eidgenössische',
            'Das erste Mal',
            'Das Tier und wir',
            'Das Urteil',
            'Das war 2015',
            'Das war 2016',
            'Das war 2017',
            'Das war 2018',
            'Das war 2019',
            'Das WEF bei SRF',
            'Das weisse Lauschen',
            'Data (Tests)',
            'Dataland',
            'Davis Cup',
            'De chli rot Traktor',
            'De Füürweehrmaa Sämi',
            'De Song vom Tag',
            'Degustationen',
            'Denk an mich',
            'Der 1. Weltkrieg',
            'Der aktuelle Expertentalk',
            'Der Alltag',
            'Der Archivar',
            'Der Berg bebt!',
            'Der Bestatter',
            'Der kleine Eisbär',
            'Der Krieg ist aus!',
            'Der Strassencheck',
            'Der Zürcher Hafenkran',
            'Desserts',
            'Deutschland hat gewählt',
            'Deutschland-Reise',
            'Deville',
            'DGST',
            'Diari',
            'Diari_old',
            'Die Älplerfamilie',
            'Die Alpenreise',
            'Die Anderen - Les Autres',
            'Die Beichte',
            'Die BuchKönig bloggt',
            'Die Bundestagswahl bei SRF',
            'Die Eröffnung',
            'Die fünfte Schweiz',
            'Die Freitagsrunde',
            'Die Gedankenexperimente',
            'Die Golfteams',
            'Die grössten Schweizer Talente',
            'Die Hörspiel-Soap',
            'Die Hilfskräfte',
            'Die Idee',
            'Die Kleinen',
            'Die Kunstjagd',
            'Die lange Form',
            'Die ModeratorInnen',
            'Die Prüfung',
            'Die reichen Schweizer',
            'Die Religion',
            'Die Schauspielschüler',
            'Die Schlussitzung',
            'Die Schweiz & der Grosse Krieg',
            'Die Schweizer',
            'Die Sendungen zur Themenwoche',
            'Die Sendungen',
            'Die Sendungen: Barock',
            'Die Tsunami-Katastrophe 2004',
            'Die TV-Serie «Real Humans»',
            'Die Wetterwoche',
            'Die Woche in Tessin Romandie',
            'Die Woche in Tessin und Romandie',
            'Die Zürcher Prozesse',
            'Die Zukunft des Internet',
            'Dienstleistungen und Kontakte',
            'Digital am Sonntag',
            'Digital Plus',
            'Digital',
            'Digitaltag',
            'Digitip',
            'Dis da litteratura 2015',
            'Dis da litteratura 2016',
            'Dis da litteratura 2017',
            'Dis da litteratura 2018',
            'Diskothek ',
            'Divers',
            'Diverse Kinderfilme & -serien',
            'Diverse Kinderhörspiele',
            'Diverse Serien',
            'Diverse',
            'DJ-Sets',
            'DOK-Filme',
            'DOK-Serien',
            'Doktor Fieberbei',
            'Doku am Donnerstag',
            'Dominik Dachs',
            'Donnschtig-Jass',
            'Doppelpunkt',
            'Dorfplatz',
            'Dossiers',
            'Drei Jahre später',
            'Dreirosenbrücke',
            'Durch dick und dünn',
            'Durchblicker ',
            'Durchsetzungs-Initiative',
            'E-Sport',
            'Ebola',
            'EBU folk festival',
            'Echo aus dem Hörsaal',
            'Echo der Zeit ',
            'Ecopop-Initiative',
            'Edi – Leben am Limit',
            'Ehe für alle',
            'Eidg. Jodlerfest',
            'Eidg. Schützenfest',
            'Eidg. Schwing- und Älplerfest',
            'Eidgenössische Vorlagen ',
            'Eidgenössisches Turnfest',
            'Ein Fall für SRF 3',
            'Ein Wort aus der Bibel ',
            'Einbürgerung',
            'Einen Monat ohne Alkohol',
            'Einfach Politik',
            'einfachluxuriös',
            'Einheitskasse',
            'Einkaufstourismus',
            'Eins für mich',
            'Einstein Online',
            'Einstein und die Folgen',
            'Einstein',
            'Eishockey allgemein',
            'Eishockey',
            'Eiskunstlaufen',
            'Elecziuns',
            'Elektronische Identität',
            'Eltern',
            'EM-Qualifikation',
            'Emil',
            'Emprendissadis',
            'En claustra',
            'Energiesteuer-Initiative',
            'Energiestrategie',
            'Energiewende',
            'Engiadina',
            'Entscheidung an der Urne',
            'Entscheidung in den USA',
            'Entscheidung',
            'Entweder/Oder',
            'Epidemiengesetz',
            'Erbschaftssteuer-Initiative',
            'Erika weiss alles',
            'Erklärvideos',
            'Ernährung der Zukunft',
            'Ernährungssicherheit',
            'Ernährungssouveränität',
            'Ersatzwahl Baselland',
            'Erste Hilfe',
            'Erstlingsfilme',
            'Erwachsen werden',
            'ESAF 2019',
            'Espresso',
            'Etiketten-Schwindel',
            'Europa League',
            'Europa',
            'Europawahlen',
            'European Championships',
            'Eurosonic',
            'Eurovision Song Contest online',
            'Eurovision Song Contest',
            'Eurovision Songcontest 2012',
            'Eusi Landchuchi',
            'Events & Shows',
            'Events',
            'Exotische Royals',
            'Expedition Hölloch',
            'Expediziun Grischun',
            'Experiment Schneuwly',
            'Experiment zuckerfrei',
            'Explain the Lyrics',
            'Exteriur',
            'Extras',
            'Extrem-OP',
            'Führungen',
            'Fünfmalklug',
            'Fabi',
            'Facebook Posts der Woche',
            'Fach-Chinesisch',
            'Fachhochschule',
            'Fachseiten',
            'Fair-Food-Initiative',
            'falsch_Filmfestival Venedig',
            'Famiglia e passatemp Surmiran',
            'Famiglia e passatemp Sursilvan',
            'Familie Biser',
            'Familie Buff',
            'Familie und Freizeit',
            'Familien-Initiative',
            'Familienartikel',
            'Familieninitiative',
            'FAQ',
            'Fascht e Familie',
            'Fasnacht 2013',
            'Fasnacht',
            'Fasten-Tagebuch',
            'Fechten',
            'Fed Cup',
            'Feiertage 2012',
            'Feine Weihnachten',
            'Ferien ohne Ärger',
            'Fernsehen',
            'Fernsehprogramme',
            'Fernweh',
            'Festa da lutga federala 2016',
            'Festas da chant e musica',
            'Festas da chant',
            'Festas da musica',
            'Festival chanzun rumantscha',
            'Festival da jazz San Murezzan',
            'Festival',
            'Festival-Player',
            'Festivalaward',
            'Festivalgeschichten',
            'Festivalgesichter',
            'Festivals',
            'Festivalsommer',
            'FIFA Frauen-WM 2015',
            'FIFA WM 2014',
            'FIFA WM 2018 History',
            'FIFA WM 2018 Live',
            'FIFA WM 2018 Resultate',
            'FIFA WM 2018 Spielplan',
            'FIFA WM 2018 Teams',
            'FIFA WM 2018 Torschützen',
            'FIFA WM 2018',
            'FIFA WM Stadien',
            'FIFA WM Teams',
            'Figuren im Interview',
            'Fiirabigmusig ',
            'Film & Serien',
            'Film Schellen-Ursli',
            'Film und Serien',
            'Film',
            'Film-Tipp',
            'Filme',
            'Filmfestival Cannes',
            'Filmfestival Locarno',
            'Filmfestival Venedig',
            'Filmfestival Zürich',
            'Filmklassiker',
            'Filmografie',
            'Filmprogramm',
            'Filmreihe am TV',
            'Filmtage 2015',
            'Filosofix',
            'Finals cuppa GR ballape',
            'Finanzordnung',
            'Fiori Musicali ',
            'Fisch',
            'Fit im Team',
            'Fit und Gesund',
            'Fit werden, fit bleiben',
            'Fiutscher',
            'Fleisch',
            'Flughafen Zürich',
            'Focus Blind Date',
            'Focus',
            'Fohrler unterwegs',
            'Folge 1: Werner Stauffacher',
            'Folge 2: Waldmann und von Flüe',
            'Folge 3:Guillaume Henri Dufour',
            'Folge 4: Escher und Franscini',
            'Food&Stories',
            'Forbidden Voices',
            'Formel 1',
            'Formular',
            'Forschung',
            'Fortpflanzungsgesetz',
            'Forum ',
            'Fotoaktion',
            'Fotoalbum der Wissenschaft',
            'Fotobox',
            'Fotowettbewerb',
            'Früh-Stück',
            'Frühe Frühchen',
            'Frühkindlicher Autismus',
            'Frankenschock',
            'Franz Hohler',
            'Franz Musil',
            'Franz Schnyder',
            'Frauen-Fussball',
            'Frauen-Nationalteam',
            'Freestyle-WM 2015',
            'Freihandel Indonesien',
            'Freitagsgast',
            'Frieden',
            'Fussball allgemein',
            'Fussball',
            'Gäste aus der Bevölkerung',
            'Gäste Bev. 8-Millionen Schweiz',
            'Gäste Bev. Olympische Wintersp',
            'Gäste Bev.&Gewerbe Einkauf',
            'Gäste Bevölkerung',
            'Gäste der Kantonsregierung LG',
            'Gäste Politik 8-Millionen CH',
            'Gäste Politik&Wirtsch. Einkauf',
            'Gäste runder Tisch',
            'Gäste und Interviews',
            'Gabalier',
            'Gadgets für KIM',
            'Game-Tipp',
            'Games',
            'Garten',
            'Garten: Kultur und Natur',
            'Gast am Mittag',
            'Gôt Miraculous',
            'Gebühren / Werbung',
            'Gedicht am Morgen',
            'Geek-Sofa',
            'Gegenentwurf Velo-Initiative',
            'Geld',
            'Geldspielgesetz',
            'General',
            'Generation Gap',
            'Geschichte des Gripen',
            'Geschichte',
            'Geschichte, Geografie',
            'Geschichten',
            'Geschichtsforschung',
            'Gesellschaft & Religion',
            'Gesellschaft im Wandel',
            'Gesellschaft, Ethik, Religion',
            'Gesichter & Geschichten',
            'Gespräche zum Jahreswechsel',
            'Gespräche',
            'Gesprächsrunden',
            'Gestalten, Musik',
            'Gesund auf Reisen',
            'Gesundheit',
            'Gesundheitswesen',
            'Gewürzroute',
            'Giacobbo / Müller',
            'Gianlucas Gesicht',
            'Gib Pass!',
            'Gieus olimpics',
            'Gieus',
            'GIFs der Woche',
            'Gion Antoni Derungs',
            'Gion Giusep Derungs',
            'Giud tribuna',
            'Glückskette aktuell',
            'Glacier-Express',
            'Glanz & Gloria',
            'Glarus und Region',
            'Glista da las gratulaziuns',
            'Glocken der Heimat',
            'Glorys',
            'Glossar',
            'Glosse',
            'Gold-Initiative',
            'Golf',
            'Gotthard',
            'Grüter & Bürgin Playlist',
            'Grüter & Bürgin',
            'Grand-Slam-Turniere',
            'Gratulationen',
            'Gratulaziuns',
            'Graubünden',
            'Gripen',
            'Grischun Central',
            'Grischun',
            'Grosis Hausmittel',
            'Grosse Interpretationen',
            'Grundeinkommen',
            'Guidelines',
            'Gurtenfestival',
            'Hüsnü hilft',
            'Hüttengeschichten',
            'Höhlen-Erlebnisse',
            'Höhlensysteme',
            'Hörbühne ',
            'Hörpunkt',
            'HörPunkt: Auf Mission',
            'HörPunkt: Glückliche Pendler? ',
            'HörPunkt: Mann Macht Frau',
            'HörPunkt: Miles Davis',
            'HörPunkt: Orchester',
            'HörPunkt: Sport-Marathon',
            'Hörspiel ',
            'Hörspiel-Klassiker',
            'Hörspiele & Geschichten ',
            'Hörspiele',
            'Hörspiele: Downloads',
            'Hörspiele: Klassiker',
            'Hörspiele: Krimi',
            'Hörspiele: Literatur',
            'Hörspiele: Mundart',
            'Hörspiele: Satire',
            'Haben Sie Töne?',
            'Haikiew',
            'Halbfinalisten',
            'Hallo Puls',
            'Hallo SRF!',
            'Handball',
            'Happy Day',
            'Hashtag der Woche',
            'Hausarztmedizin',
            'HbbTV IKON',
            'Heilkraft aus der Natur',
            'Heiratsstrafe',
            'Helden des Alltags',
            'Helden des Internets',
            'Hello Again!',
            'helveCHia',
            'Helvetia',
            'Herzblut',
            'Heute aktuell ',
            'Heute um Fünf',
            'Heute um halb fünf',
            'Heute um Vier',
            'HeuteMorgen',
            'Hidden Helvetia',
            'Hier mit dir',
            'Highlights',
            'Hilfe',
            'Hilfe: Internet',
            'Himmelblau – Leben am Limit',
            'Hinter den Kulissen',
            'Hintergründe',
            'Hinweis',
            'History',
            'Hit-Welle',
            'Hitparade',
            'Hits e semperverds africans',
            'Hochhäuser',
            'Hockey regiunal',
            'Hoffnung ',
            'Hommage an Claude Nobs',
            'Hommage',
            'Hornkuh-Initiative',
            'Horoskop',
            'Hunkeler',
            'Ich oder Du',
            'Ich schänke dir es Lied',
            'Ich, die Mehrheit',
            'Il chavazzin dal di',
            'Il cumpliment',
            'Il film rumantsch',
            'Il forum 2007-2008',
            'Il forum 2009-2010',
            'Il forum 2011-2012',
            'Il forum 2013-2014',
            'Il forum 2015-2016',
            'Il forum',
            'Il Patnal 1970-1971',
            'Il Patnal 1972-1973',
            'Il Patnal 1974-1975',
            'Il Patnal',
            'Ils auters',
            'Im Fokus',
            'Im Konzertsaal ',
            'Im Schatten der Burg',
            'Im Schatten von',
            'Immer dä Michel',
            'Impuls',
            'In der Limo mit ...',
            'In eigenen Worten',
            'In eigener Sache',
            'Ina chanzun – in\'istorgia',
            'Ina chanzun – in’istorgia',
            'Industrie 4.0',
            'Info 3 ',
            'Infografik',
            'Infografiken',
            'Information',
            'Inhaltselemente',
            'Initiative Grüne Wirtschaft',
            'Initiative Kapitalbesteuerung',
            'Initiative Pestizidverbot',
            'Initiative Verhüllungsverbot',
            'Inked',
            'Input',
            'Interaktiv',
            'International',
            'Internationale Acts',
            'Internationale Ligen',
            'interner Gebrauch',
            'Interpresa RTR',
            'Interviews LG Glarus',
            'Interviews',
            'Intranet RTR',
            'Isobarenkarte',
            'Istorgia',
            'Istorgia_old',
            'Italiens neue Regierung',
            'Ivo und die Backdetektive',
            'Ja oder Nein',
            'Jagdgesetz',
            'Jahresrückblick 2012',
            'Jahresrückblick 2013',
            'Jahresrückblick 2014',
            'Jahresrückblick 2015',
            'Jahresrückblick',
            'Jass-Service',
            'Jassen',
            'Jazz aktuell',
            'Jazz Classics',
            'Jazz Collection',
            'Jazz in der Schweiz',
            'Jazz Live',
            'Jazz',
            'Jazzfestival Schaffhausen',
            'Jeder Rappen zählt Camp',
            'Jeder Rappen zählt',
            'Jetzt reden wir!',
            'Jobs und Ausbildung',
            'Jodlerfest Brig',
            'Jodlerfest Davos',
            'JRZ Social',
            'Jukebox ',
            'Jung und arbeitslos in Europa',
            'Junge Kunst in der Schweiz',
            'Jura-Abstimmung',
            'Künstler-Porträts',
            'Körper & Geist',
            'Kabarettisten erklären Jazz',
            'Kalabrese DJ-Mix',
            'Kalorienbedarf',
            'Kampfjet-Gripen Ja oder Nein?',
            'Kampfjetbeschaffung',
            'Kampfzone Bikini',
            'Kandidaten 2017',
            'Kantone und Gemeinden',
            'Kantone Wahlen15',
            'Kantone',
            'Kantonsfusion Basel',
            'Karussell',
            'Kassensturz',
            'Kassensturz-Tests',
            'Kaufrecht',
            'Kids',
            'Kilchspergers Jass-Show',
            'Kinder & Familie ',
            'Kinder / Jugendliche',
            'Kinder',
            'Kinder-News',
            'Kinderabzüge',
            'Kindergrösse',
            'Klangfenster',
            'Klassik',
            'Klassiktelefon',
            'Klimaerwärmung',
            'Klischees und Fakten',
            'Knack und Nuss',
            'Kochen & Backen',
            'Kochen',
            'Kochtipps',
            'Kommentare',
            'Kommunal',
            'Kompass',
            'Konsum',
            'Konsumenzler',
            'Kontext ',
            'Konzernverantwortung',
            'Konzert und Oper',
            'Konzert/Oper',
            'Konzertvideos',
            'Korrespondentennetz',
            'Kreuz & Queer',
            'Krieg und Kultur',
            'Kriegsgeschäfte-Initiative',
            'Krimi & True Crime',
            'Krimi',
            'Kriminal-Einmaleins',
            'Krimis: mörderischer Lesespass',
            'Kuhkampf',
            'Kultur & Religion ',
            'Kultur - Gratis',
            'Kultur aktuell ',
            'Kultur kompakt',
            'Kultur weltweit',
            'Kultur',
            'Kultur-Stammtisch',
            'KULTURADVENT',
            'Kulturknigge',
            'Kulturplatz',
            'Kunst des Widerstands',
            'Kunst',
            'Kunstturnen',
            'Kurse',
            'Kurt Früh Reloaded',
            'Kurzhörspiele Filosofix',
            'La cifra',
            'La classica',
            'La populara',
            'La stailalva',
            'La truvaglia',
            'Lahti 2017',
            'Lai 2018',
            'Landessprachen',
            'Landesteile Vorurteile',
            'Landesverrat',
            'Landfrauenküche',
            'Landingpages',
            'Landquart',
            'Landsgemeinde Glarus',
            'Landsgemeinde',
            'Langlauf',
            'Las perlas',
            'Late Night Concert',
            'Late Night Jazz',
            'Leben & Alltag',
            'Leben am Limit',
            'Leben mit Parkinson',
            'Leben vor 500 Jahren',
            'Lebensgeschichte',
            'Leichtathletik',
            'Leichtathletik-EM',
            'Leichtathletik-WM',
            'Leipziger Buchmesse',
            'Lernen – gewusst, wie',
            'Lernende',
            'Lesung ',
            'Let\'s Play',
            'Let\'s Say',
            'Lexicon A',
            'Lexicon B',
            'Lexicon C',
            'Lexicon D',
            'Lexicon E',
            'Lexicon F',
            'Lexicon G',
            'Lexicon H',
            'Lexicon I',
            'Lexicon J',
            'Lexicon K',
            'Lexicon L',
            'Lexicon M',
            'Lexicon N',
            'Lexicon O',
            'Lexicon P',
            'Lexicon Q',
            'Lexicon R',
            'Lexicon S',
            'Lexicon T',
            'Lexicon U',
            'Lexicon V',
            'Lexicon W',
            'Lexicon X',
            'Lexicon Y',
            'Lexicon Z',
            'Lexicon',
            'Liebesbriefe',
            'Lifestyle',
            'Linard Bardill',
            'Linguarias',
            'Literatur',
            'Literaturclub',
            'Literaturfenster Schweiz',
            'Live die Rubrik',
            'Live en RR',
            'Live tar RTR',
            'Live',
            'Live-Chat',
            'Live-Konzert',
            'Livecenter-Teaser',
            'Lokaltermin',
            'Lost & Found Playlist',
            'Lost & Found',
            'Lust und Last des Alters',
            'Lutga',
            'Luzern',
            'Lyrik am Mittag',
            'L\'archiv sco memoria',
            'L\'archivar recumonda',
            'L\'instrumentala',
            'Männerküche',
            'Märchen: Artikel',
            'Märchen: Netzmarie',
            'Märchen: Radio-Sendungen',
            'Märchen: TV-Sendungen',
            'Märchen: Webvideos',
            'Märchenhaft',
            'Madame Etoile',
            'Magazin da cultura',
            'Mailbox',
            'Making of «Der Bestatter»',
            'Making Of',
            'Making of',
            'Maloney',
            'Mani Luegt',
            'Maraton da skis 2015',
            'Maraton da skis 2016',
            'Maraton da skis 2017',
            'Maraton da skis 2018',
            'Maraton da skis 2019',
            'Maraton da skis engiadinais',
            'Marella',
            'Margrits Alpenküche',
            'Markenlizenzen',
            'Marktangebote',
            'Mascha und dä Bär',
            'Masseneinwanderungs-Initiative',
            'Mathematik',
            'Mauerfall (aktuell): Sendungen',
            'Mauerfall: Übersicht',
            'Mauerfall: Die Mauer',
            'Mauerfall: Geschichten',
            'Mauerfall: Sendungen',
            'Medias 2015',
            'Medias 2016',
            'Medias 2017',
            'Medias 2018',
            'Medias 2019',
            'Medias 2020',
            'Medias 2021',
            'Medias',
            'Medien und Informatik',
            'Medienclub',
            'Medienforum',
            'Medienmitteilungen',
            'Medienpartnerschaften',
            'Medizin',
            'Mehr Sport',
            'Mehr zur Sendung',
            'Mein Haustier',
            'Mein Hobby',
            'Mein Lieblingslied',
            'Meine fremde Heimat',
            'Meine Räder - mein Leben',
            'Meme des Jahres 2012',
            'Mensch',
            'Menschen & Gesellschaft',
            'Menschen der Raststätte',
            'Menschen im Bundeshaus',
            'Menschen und Horizonte',
            'Menschmaschine',
            'Mental X Essential Tunes',
            'Mental X Playlist',
            'Mental X Playlisten',
            'Mental X',
            'Merkblätter',
            'Mes vitg ed jau',
            'Meteo',
            'Meteo-Stories',
            'Michel muss mal',
            'Michel trifft...',
            'Midterm Elections 2014',
            'Mietrecht',
            'Mietwohnungs-Initiative',
            'Mindestlohn-Initiative',
            'Mini Chuchi, dini Chuchi',
            'Mini Räder - Mis Läbe',
            'Mini zwei Dihei',
            'Mint',
            'Miss Schweiz',
            'Mission B',
            'Missiun B',
            'Mister Schweiz',
            'Mit «Espresso» in die Zukunft',
            'Mit dem Rucksack um die Welt',
            'Mitmachen',
            'Mobilität',
            'Moderation',
            'Moderatoren und Standorte',
            'Moderatoren',
            'Momentaufnahmen',
            'Morgengast',
            'Morgengeschichte ',
            'Morgenstund - Finalspiel',
            'Morgenstund hat Gold im Mund - Finalspiel',
            'Morgenstund hat Gold im Mund',
            'Motocross',
            'Motorrad',
            'Motorsport allgemein',
            'Motorsport',
            'Mountainbike',
            'Multimedia',
            'Multimediale Angebote',
            'Mundart',
            'Muotathaler Wetterschmöcker',
            'Musica',
            'Musik aktuell',
            'Musik der Welt',
            'Musik für einen Gast',
            'Musik unserer Zeit',
            'Musik',
            'Musik+ Tempo',
            'Musik+',
            'Musik-Blog',
            'Musikabend',
            'Musikmagazin',
            'Musikpavillon',
            'Musikplus',
            'Musikwelle aktuell',
            'Musikwelle Magazin',
            'Mutterstadt',
            'MwSt-Initiative',
            'mx3',
            'My Story',
            'Myriam und die Meisterbäcker',
            'Nach dem Ja',
            'Nachhaltigkeit',
            'Nachklang',
            'Nachrichten',
            'Nachrichtendienst-Gesetz',
            'Nachtclub mit Ralph Wicki',
            'Nachtexpress ',
            'Nachtexpress',
            'Nachtflug',
            'Nachtgedanken',
            'Nachtschwärmer',
            'nachtwach',
            'Nahrungsmittel-Spekulation',
            'National League',
            'Nationalhymnen',
            'Nationalmannschaft',
            'Nations League',
            'Natur & Tiere',
            'Naziunal/Internaziunal',
            'NETZ NATUR',
            'Netz Natur',
            'Netzwelt',
            'Neu im Musikprogramm',
            'Neue EU-Waffenrichtlinie',
            'Neue Musik auf SRF Musikwelle',
            'Neue Musik im Konzert',
            'Neue/er/es Rubrik',
            'Neuer Schweizer Stoff',
            'New Rubrik',
            'News App',
            'News und Hintergründe',
            'News',
            'Newsevent',
            'Newsletter',
            'NHL',
            'nicht verwenden',
            'Ninas Reise-Tagebuch',
            'Noch mehr Festivals',
            'NONONO: Glückliche Pendler?',
            'Nord. Kombination',
            'Nordische Ski-WM',
            'Noss chors',
            'Nossa litteratura',
            'Notturno ',
            'Nouvo',
            'Nr. 47',
            'Nua è Stefan?',
            'Nus eran là - Vus eras là',
            'Occurrenzas',
            'Offerta publicistica',
            'Olá Brasil',
            'Olis Mega Vlog',
            'Olympia 2022',
            'Olympia History',
            'Olympische Spiele',
            'Olympische Sternstunden',
            'Olympische Winterspiele 2022',
            'Ombudsstelle',
            'On The Road Again',
            'Open Air Gampel',
            'Open Air Lumnezia 2015',
            'Open Air Lumnezia 2016',
            'Open air Lumnezia 2017',
            'Open Air Lumnezia',
            'Open Air St. Gallen',
            'Openair Avers',
            'Openair Frauenfeld',
            'Openair Hohen Rätien',
            'OpenAir St. Gallen',
            'Opernführer',
            'Organisation',
            'Organisaziun',
            'Orientierungslauf',
            'OSCAR-GEWINNER',
            'Oscars',
            'Ostschweiz',
            'Outdoor-Reporter',
            'Outtakes',
            'Pädophilen-Initiative',
            'Pätagei',
            'Pachet d\'advent',
            'Palaver',
            'Panorama',
            'Papstwahl',
            'Paralympics',
            'Parlando',
            'Parteien im Vergleich',
            'Parteien',
            'Partenadis',
            'Partenaris e sponsuradi',
            'Partner',
            'Party! Party!',
            'Passage',
            'Pauschalbesteuerung',
            'Peach Weber',
            'People',
            'Persönlich',
            'Personelles',
            'Personen Poträts',
            'Perspektiven ',
            'PET -  das Satiremagazin',
            'PET - das Satiremagazin ',
            'Peter Schneider',
            'Pferde in der Schweiz',
            'Philip Maloney',
            'Philo-Slam',
            'Philosophie Selbsttest',
            'Physik, Chemie, Biologie',
            'Pingu',
            'Plazzas e scolaziun',
            'Pled rumantsch 2016',
            'Pled rumantsch 2017',
            'Pled Rumantsch',
            'Pled rumantsch',
            'Plus trais grads',
            'Podcast «Zambo-Bus»',
            'Podcast',
            'Podcasts',
            'Polenta Jam',
            'politbox on tour – Bad Bonn',
            'politbox on tour – Basel',
            'politbox on tour – Bern',
            'politbox on tour – ETH',
            'politbox on tour – Freiburg',
            'politbox on tour – Genève',
            'politbox on tour – Grüsch',
            'politbox on tour – JKF',
            'politbox on tour – Kreuzlingen',
            'politbox on tour – Lausanne',
            'politbox on tour – LCdF',
            'politbox on tour – Lugano',
            'politbox on tour – Luzern',
            'politbox on tour – Murten',
            'politbox on tour – St. Gallen',
            'politbox on tour – Visp',
            'politbox on tour – Winterthur',
            'politbox on tour – Zürich',
            'Politik & Wirtschaft ',
            'Politikum',
            'Pollenbelastung',
            'Pop Routes',
            'Porträt',
            'Porträttexte',
            'Pot au Puls',
            'Potzmusig (Radio)',
            'Potzmusig Radio',
            'Potzmusig',
            'Präimplantationsdiagnostik',
            'Praktika und Stages',
            'Praticum e stage',
            'Predigt',
            'Premi SRG.R',
            'Profil',
            'Promi-Playlisten',
            'Promi-Quiz',
            'Prominent gedacht',
            'Promis virtuell',
            'Protagonisten',
            'Proverbi da la fin d\'emna',
            'Psyche',
            'Publicaziuns',
            'Publikationen',
            'Publikumsfragen',
            'Publizistisches Angebot',
            'Puls in Lourdes',
            'Puls',
            'Puls-Chor',
            'Purtret',
            'Purtrets da professiun',
            'Purtrets',
            'Puter',
            'Pyeongchang 2018',
            'Pyeongchang Livestreams',
            'Pyeongchang Medaillen',
            'Pyeongchang Resultate',
            'Pyeongchang Schweizer',
            'Pyeongchang Zeitplan',
            'Pyeongchang',
            'Qua na sun jau anc mai stà',
            'Qualität',
            'Quartier',
            'Querfeldeins',
            'Quiz & Games',
            'Quiz',
            'Rückblick 2012',
            'Rückblick 2013 ',
            'Rückblick 2014',
            'Rückblicke 2015',
            'Rückruf',
            'Rad',
            'Radar',
            'Radio SRF 1',
            'Radio SRF 2 Kultur',
            'Radio SRF 4 News',
            'Radio SRF Musikwelle',
            'Radio',
            'Radio-Sponsoring',
            'Radioarchiv',
            'Radiogottesdienst',
            'Radioprogramme',
            'Radioscola 1955-1960',
            'Radioscola 1961-1965',
            'Radioscola 1966-1970',
            'Radioscola 1971-1972',
            'Radioscola 1973-1974',
            'Radioscola 1975',
            'Radioscola',
            'Raffiniert',
            'Ralph und die Dinosaurier',
            'Rapport annual',
            'Ratgeber ',
            'Ratgeber',
            'Raumplanungsgesetz',
            'Ready, Steady, Golf!',
            'Ready, Steady, Golf',
            'Recepziun',
            'Rechtliches',
            'Rechtsfragen',
            'Reflexe',
            'Reggae Special',
            'Regierungsrat Glarus',
            'Regiojournal Aargau Solothurn',
            'Regiojournal Basel Baselland ',
            'Regional Diagonal',
            'Regional',
            'Regionaljournal  Ostschweiz',
            'Regionaljournal Aargau Solothurn',
            'Regionaljournal Basel Baselland',
            'Regionaljournal Bern ',
            'Regionaljournal Bern Freiburg Wallis',
            'Regionaljournal Graubünden ',
            'Regionaljournal Luzern',
            'Regionaljournal Ostschweiz ',
            'Regionaljournal Zürich Schaffhausen',
            'Regionaljournal Zürich',
            'Regionaljournal Zentralschweiz',
            'Regionalstudios',
            'Regionen',
            'Regiunal',
            'Rehmann',
            'Reihen',
            'Reisegeschichten',
            'Reisen',
            'Reisetagebuch Alaska',
            'Reiten',
            'Rendez-vous ',
            'Rendez-vous mit der Welt',
            'Rentenreform',
            'Reportagen und Hintergründe',
            'Reporter',
            'Resultate & Tabellen',
            'Resultate',
            'Resultatefinder',
            'Reto Stalders Fototagebuch',
            'RetrOrachel',
            'rezept 1',
            'rezept 2',
            'Rezepte ',
            'Rezepte 2010',
            'Rezepte 2011',
            'Rezepte 2012',
            'Rezepte 2013',
            'Rezepte 2014',
            'Rezepte 2015',
            'Rezepte 2016',
            'Rezepte 2017',
            'Rezepte 2018',
            'Rezepte 2019',
            'Rezepte 2020',
            'Rezepte 2021',
            'Rezepte «SRF bi de Lüt – Live»',
            'Rezepte Die grosse Grillshow',
            'Rezepte Eiskalt serviert',
            'Rezepte Eusi Landchuchi 2015',
            'Rezepte Eusi Landchuchi 2016',
            'Rezepte Eusi Landchuchi 2017',
            'Rezepte Eusi Landchuchi 2019',
            'Rezepte Eusi Landchuchi 2021',
            'Rezepte Goldenes Rüebli',
            'Rezepte Schwiizer Chuchi 1',
            'Rezepte Schwiizer Chuchi 2',
            'Rezepte Schwiizer Chuchi 3',
            'Rezepte SRF bi de Lüt',
            'Rezepte',
            'RHC',
            'Riesenreich Russland',
            'Rio 2016 Videos',
            'Rio 2016',
            'Rio am TV',
            'Rio Medaillen',
            'Rio Medaillenspiegel',
            'Rio Player',
            'Rio Programm',
            'Rio Resultate',
            'Rio Schweizer Team',
            'Rio XX Zeitplan',
            'Rio Zeitplan',
            'Rio',
            'Risiko',
            'Roboter im Film',
            'Roboter und Gesellschaft',
            'Roboter wie wir',
            'Roboter-Technologie',
            'Rock / Pop',
            'Rock Special',
            'Rosanna checkt\'s!',
            'Round Table Knights DJ-Mix',
            'Royal',
            'RtiR',
            'RTR mx3',
            'RTR Purple Nights',
            'RTR – mia playlist',
            'RTRintern',
            'Rubrik für Tests (Entwickler)',
            'Rudern',
            'Rugby',
            'Rumantsch Grischun',
            'Rumantsch, what else?',
            'Rund um den Flughafen',
            'Rundschau spezial',
            'Rundschau talk',
            'Rundschau',
            'Rundum Politik',
            'SAC-Hütte',
            'Sakral-vokal',
            'Salut la France',
            'Sammlung Dür',
            'Samschtig-Jass',
            'Samstagsrundschau',
            'San Murezzan 2017',
            'Sand – das neue Gold',
            'Satellitenbild',
            'Satire & Comedy ',
            'Satire',
            'Schaffhausen',
            'Schatzjäger',
            'Schauspieler',
            'Schiessen',
            'Schladming 2013',
            'Schlag auf Schlager',
            'Schlager',
            'Schlagermosaik',
            'Schlauer in 60 Sekunden',
            'Schluss mit lustig',
            'Schlussendlich Schwul*Lesbisch',
            'Schlusspunkt',
            'Schmirinski\'s',
            'Schnabelweid',
            'Schnabelweid-Briefkasten',
            'Schnee',
            'Schneeprognose',
            'Schneewetter',
            'Schnipseljagd',
            'Schr@ges Web',
            'Schreckmümpfeli',
            'Schulbesuch',
            'Schweiz aktuell am Berg',
            'Schweiz aktuell am Gotthard',
            'Schweiz aktuell',
            'Schweiz',
            'Schweizer Acts',
            'Schweizer Brauchtum',
            'Schweizer Buchpreis 2013',
            'Schweizer Buchpreis 2014',
            'Schweizer Buchpreis 2015',
            'Schweizer Buchpreis',
            'Schweizer Cup',
            'Schweizer Film',
            'Schweizer Filmpreis',
            'Schweizer Filmquiz',
            'Schweizer Frauen-Nati',
            'Schweizer Gesangfest Meiringen',
            'Schweizer Geschichten',
            'Schweizer Jugend testet',
            'Schweizer Musik',
            'Schweizer Nationalmannschaft',
            'Schweizer Sagen',
            'Schweizer Wirtschaft im Fokus ',
            'Schwiiz und dütlich',
            'Schwiizer Chuchi mit Ivo Adam',
            'Schwimmen',
            'Schwingen',
            'Scriver è cool',
            'Scuntrada - La marella 1977',
            'Scuntrada - La marella 1978',
            'Scuntrada - La marella 1979',
            'Scuntrada - La marella 1980',
            'Scuntrada - La marella 1981',
            'Scuntrada - La marella 1982',
            'Scuntrada - La Marella',
            'Sechseläuten',
            'Seefeld 2019',
            'Segeln',
            'Seitentriebe',
            'Selbstbestimmungs-Initiative',
            'Selbstgemacht',
            'Sendetechnik',
            'Sendung',
            'Sendungen (Locarno)',
            'Sendungen «Gewürzroute»',
            'Sendungen im TV und Radio',
            'Sendungen zum Thema',
            'Sendungen',
            'Sendungen/Anlässe',
            'Sendungen: Jazz in der Schweiz',
            'Sendungsbesuche',
            'Sendungskosten allgemein',
            'Sendungskosten',
            'Sendungsporträt',
            'Senioren-Magazin',
            'Serias',
            'Serie: So liebt die Welt',
            'Serien & Filme',
            'Serien und Specials',
            'Serien',
            'Serientipps',
            'Servetschs',
            'Service public',
            'Service-public-Initiative',
            'Services',
            'Session',
            'SF unterwegs',
            'Showcase',
            'Silvesterstadl',
            'Sin il viv!',
            'Sinerzyt',
            'Singlemodul-fullwith',
            'Ski alpin allgemein',
            'Ski Alpin',
            'Ski alpin',
            'Ski Freestyle',
            'Ski nordic Falun 2015',
            'Skip or Watch',
            'Skispringen',
            'Slam 2018',
            'Slam Poeten',
            'Snowboard',
            'So tönts',
            'Social Fun-Attack',
            'Solar Impulse 2',
            'Solothurner Filmtage',
            'Solothurner Literaturtage 2013',
            'Solothurner Literaturtage 2014',
            'Solothurner Literaturtage',
            'Sommerkonzerte',
            'Sommerserie 2013',
            'Sommerserie «Anfänge»',
            'Sommerserie «Extrem!»',
            'Sommerserie «Pioniere»',
            'Sommerserie',
            'Son Niclà e Nadal Surmiran',
            'Son Niclà e Nadal Sursilvan',
            'Songmates',
            'Songs & Alben',
            'Songs der Woche',
            'Sonstiges Recht',
            'Sorge ',
            'Sotschi im TV',
            'Sotschi',
            'Soundcheck',
            'Sounds!',
            'Spaniens verlorene Generation',
            'Spasspartout',
            'Specials',
            'Spengler Cup',
            'Spezial',
            'Spiele',
            'Spitalgeschichten',
            'Sponsoring-Richtlinien',
            'Sponsuradis',
            'Sport App',
            'Sport Divers',
            'Sport im Gespräch',
            'Sport',
            'Sportissimo',
            'sportpanorama',
            'Sportradio',
            'Sports Awards',
            'Spot on!',
            'Spotter',
            'Spotterplätze',
            'Sprachen',
            'SRF 2 Kultur Extra',
            'SRF 2 Kultur Live',
            'SRF 2 Kultur Musik',
            'SRF 2015 – Audios und Videos',
            'SRF 3 -  oder nit?',
            'SRF 3 - oder nit?',
            'SRF 3 Best Talent',
            'SRF 3 chocht fein ',
            'SRF 3 eingeliefert',
            'SRF 3 Futebol Total ',
            'SRF 3 Hitparade',
            'SRF 3 Live Session',
            'SRF 3 macht Agglo',
            'SRF 3 macht es Büro uf ',
            'SRF 3 Pop-Archiv',
            'SRF 3 punkt CH',
            'SRF 3 Wirtschaft',
            'SRF 3 zeigt Flagge',
            'SRF 4 aktuell',
            'SRF 4 News - A Bancada do Brasil',
            'SRF 4 News Digital',
            'SRF 4 News Medientalk',
            'SRF 4 News Spezial',
            'SRF 4 News Talk',
            'SRF 4 News Wirtschaftswoche',
            'SRF 4 News Zeitblende',
            'SRF 4 Tageschronik',
            'SRF App',
            'SRF Börse',
            'SRF bewegt',
            'SRF bi de Lüt – Live online',
            'SRF bi de Lüt – Live',
            'SRF bi de Lüt – Männerküche',
            'SRF bi de Lüt – Wunderland',
            'SRF bi de Lüt',
            'SRF Data',
            'SRF DOK',
            'SRF Fashion Week',
            'SRF Forward',
            'SRF Impact',
            'SRF in Interlaken',
            'SRF Kinder News',
            'SRF Kulturclub',
            'SRF Musikwelle Brunch',
            'SRF News Styleguide',
            'SRF school',
            'SRF Schweizer Film',
            'SRF Website',
            'srfzämestah',
            'SRG.R',
            'St. Gallen',
            'St. Moritz 2017',
            'Stadien Frauen-WM',
            'Stadien',
            'Stadt Land Talent',
            'Standorte',
            'Stars',
            'Start-up',
            'Start-up-Woche',
            'Stellenmarkt',
            'Sterchis Welt',
            'Sternstunde Kunst',
            'Sternstunde Musik',
            'Sternstunde Philosophie auf Radio SRF 2 Kultur',
            'Sternstunde Philosophie',
            'Sternstunde Religion',
            'Stil-Tipp',
            'Stimmen zu Früh',
            'Stipendien-Initiative',
            'Strassenfonds',
            'Struktur / Technik',
            'Studi&Chill',
            'Studio Basel',
            'Studio Bern',
            'Studio Zürich Brunnenhof',
            'Studio Zürich Leutschenbach',
            'Suisse Quiz',
            'Super Bio Heroes',
            'Super League',
            'Surf- und Segelwetter',
            'Surmiran',
            'Surselva Jam 2017',
            'Surselva Jam 2018',
            'Surselva Jam',
            'Surselva',
            'Sursilvan',
            'Survista',
            'Sutsilvan',
            'Suvlaki, Gyros e Capretta',
            'Svizra',
            'Swiss Economic Forum 2014 ',
            'Swiss Economic Forum 2015',
            'Swiss Economic Forum',
            'Swiss League',
            'Swiss Music Awards',
            'SwissAward History',
            'SwissAward',
            'Swissmade',
            'Sykora Gisler',
            'Töfflibuebe',
            'Tabula Rasa',
            'Tag und Nacht',
            'Tagebuch',
            'Tagesabstimmungen',
            'Tagesgespräch ',
            'Tagesgespräch-Chat',
            'Tagesschau',
            'Talk nach Mitternacht ',
            'Talk',
            'Tatort',
            'Team SRF Musikwelle',
            'Teams Frauen-WM',
            'Teaser',
            'Technik',
            'Tennis allgemein',
            'Tennis',
            'Terrorismus-Gesetz',
            'Tessiner Gemeinden',
            'Test',
            'test',
            'Test-Länderspiele',
            'Testcase',
            'testli',
            'testrubrik',
            'Tests',
            'Testsieger',
            'Tete A Tete',
            'Text zum Sonntag',
            'Theke',
            'Themen',
            'Themenschwerpunkte',
            'Thementag 1. WK',
            'Thun',
            'Ticker',
            'Tierarzt',
            'Time to swing!',
            'Timo und Paps',
            'Tipps',
            'Tips trics e tacs',
            'Tokyo 2020',
            'Tonreisen',
            'Tools',
            'Top Pop Rumantsch',
            'Total Birgit',
            'Total local',
            'Tram Region Bern',
            'Trampolin - uffants e medias',
            'Trap Kitchen Warriors',
            'Trap Kitchen',
            'Trauer um Nelson Mandela',
            'Traumberuf',
            'Traumhochzeit in Schweden',
            'Treatment Award',
            'Treffpunkt',
            'Trend ',
            'Triathlon',
            'Trick 77',
            'Trigger – Kurzfilm der Woche',
            'Trinkwasser-Initiative',
            'True Life',
            'True Talk',
            'TS-Wahlserie',
            'Tschipo',
            'Tunnelgeschichten',
            'Turnea da festivals 2018',
            'Turnea da festivals 2019',
            'Turnea da festivals',
            'TV',
            'TV-Serien: Kult und Kultur',
            'TV-Sponsoring',
            'Tweets der Woche',
            'U21',
            'UEFA Euro 2016 Videos',
            'UEFA EURO 2016',
            'UEFA EURO 2020 Resultate',
            'UEFA EURO 2020 Spielplan',
            'UEFA EURO 2020 Teams',
            'UEFA EURO 2020 Torschützen',
            'UEFA EURO 2020',
            'UEFA Frauen-EURO 2017',
            'Ueli Schmezer',
            'Uf Takt',
            'Uf u dervo',
            'Uffants',
            'Ulteriur Grischun',
            'Umfrage',
            'Umfragen',
            'Umstrittene Fussball-WM',
            'Umwelt und Verkehr',
            'Uni-Transparenz',
            'Unihockey',
            'Universität',
            'Unnütze Web-Fundstücke',
            'Unsere Kritiker',
            'Unspunnen 2017',
            'Unterhaltung',
            'Unterhaltungs-Sendungen',
            'Unternehmen',
            'Unternehmenssteuer',
            'Unterwegs in Deutschland',
            'Unzipped',
            'Uorschla Cranzla recloma',
            'Uorsin Schellen-Ursli',
            'Urnerboden',
            'US-Fernsehserien',
            'US-Wahlen',
            'UX-Testing',
            'Vail / Beaver Creek 2015',
            'Vail 2015',
            'Valladas talianas',
            'Vallader',
            'Vancouver Moments',
            'Varieté, Feste & Umzüge',
            'Vaterschaftsurlaub',
            'Vegetarisch',
            'Veni Vidi Venderdi',
            'Veranstaltungen',
            'Vergissi nümm',
            'Vergleich GL/BS Landsgemeinde ',
            'Verkehrsfinanzierung',
            'Verlosung',
            'Versets e poesias (Puter)',
            'Versets e poesias (Surmiran)',
            'Versets e poesias (Sursilvan)',
            'Versets e poesias (Sutsilvan)',
            'Versets e poesias (Vallader)',
            'Versets e poesias',
            'Versicherungen',
            'Versuchskaninchen',
            'Vertiefung',
            'Vetters Töne',
            'Video-Austausch',
            'Videos & Bilder',
            'Videos und Audios vom WEF 2016',
            'Videos und Audios zum Thema',
            'Videos und Audios zur Vorlage',
            'Videos von & für Lehrpersonen',
            'Videos',
            'Vio tranter trais',
            'VIP-Archiv',
            'Virtual Reality',
            'Virus Life',
            'Visite',
            'Vita capita – radionovela',
            'Vita e cretta',
            'Viva la Diva',
            'Viva Volksmusik',
            'VoD',
            'VOD-Angebot',
            'Vogelperspektiven',
            'Voilà la France',
            'Volkskultur',
            'Volksmusik / Schlager',
            'Volksmusik Aktuell',
            'Volksmusik',
            'Volksmusik-Brunch',
            'Volksmusikfest',
            'Volkswahl Bundesrat',
            'Volleyball',
            'Vollgeld-Initiative',
            'Vom Spinner zum Gewinner',
            'Vorspeisen',
            'Votaziuns',
            'Wünsch dir was',
            'Wagner im Ring',
            'Wagnis Wildnis – Protagonisten',
            'Wagnis Wildnis',
            'Wahl-Arena',
            'Wahl-Lokal',
            'Wahlbarometer',
            'Wahlen 15',
            'Wahlen 2019 Aargau',
            'Wahlen 2019 Ausserrhoden',
            'Wahlen 2019 Basel-Stadt',
            'Wahlen 2019 Baselland',
            'Wahlen 2019 Bern',
            'Wahlen 2019 Freiburg',
            'Wahlen 2019 Genf',
            'Wahlen 2019 Glarus',
            'Wahlen 2019 Graubünden',
            'Wahlen 2019 Innerrhoden',
            'Wahlen 2019 Jura',
            'Wahlen 2019 Kantone',
            'Wahlen 2019 Luzern',
            'Wahlen 2019 Neuenburg',
            'Wahlen 2019 Nidwalden',
            'Wahlen 2019 Obwalden',
            'Wahlen 2019 Schaffhausen',
            'Wahlen 2019 Schwyz',
            'Wahlen 2019 Solothurn',
            'Wahlen 2019 St. Gallen',
            'Wahlen 2019 Tessin',
            'Wahlen 2019 Thurgau',
            'Wahlen 2019 Uri',
            'Wahlen 2019 Waadt',
            'Wahlen 2019 Wallis',
            'Wahlen 2019 Zürich',
            'Wahlen 2019 Zug',
            'Wahlen 2019',
            'Wahlen AR',
            'Wahlen Baden',
            'Wahlen BE',
            'Wahlen Bern',
            'Wahlen BS',
            'Wahlen FR',
            'Wahlen GL',
            'Wahlen Glarus - Regierungsrat',
            'Wahlen Glarus',
            'Wahlen GR',
            'Wahlen Graubünden',
            'Wahlen Grenchen',
            'Wahlen in Grossbritannien',
            'Wahlen LU',
            'Wahlen Luzern',
            'Wahlen Nidwalden',
            'Wahlen NW',
            'Wahlen Obwalden',
            'Wahlen Olten',
            'Wahlen OW',
            'Wahlen Schaffhausen',
            'Wahlen SG',
            'Wahlen SO',
            'Wahlen Solothurn 2013',
            'Wahlen St. Gallen',
            'Wahlen St. Moritz',
            'Wahlen Stadt Zürich',
            'Wahlen TG',
            'Wahlen und Abstimmungen AG',
            'Wahlen und Abstimmungen Bern',
            'Wahlen und Abstimmungen BS',
            'Wahlen und Abstimmungen FR',
            'Wahlen VD',
            'Wahlen VS',
            'Wahlen Winterthur',
            'Wahlen Zürich',
            'Wahlen Zug',
            'Wahlen',
            'Wahlen15 Aargau',
            'Wahlen15 Ausserrhoden',
            'Wahlen15 Basel Stadt',
            'Wahlen15 Baselland',
            'Wahlen15 BE',
            'Wahlen15 Bern',
            'Wahlen15 Freiburg',
            'Wahlen15 Genf',
            'Wahlen15 Glarus',
            'Wahlen15 Graubünden',
            'Wahlen15 Innerrhoden',
            'Wahlen15 Jura',
            'Wahlen15 Luzern',
            'Wahlen15 Neuenburg',
            'Wahlen15 Nidwalden',
            'Wahlen15 Obwalden',
            'Wahlen15 politbox',
            'Wahlen15 Schaffhausen',
            'Wahlen15 Schwyz',
            'Wahlen15 Solothurn',
            'Wahlen15 St. Gallen',
            'Wahlen15 Tessin',
            'Wahlen15 Thurgau',
            'Wahlen15 Uri',
            'Wahlen15 Waadt',
            'Wahlen15 Wahlhilfe',
            'Wahlen15 Wallis',
            'Wahlen15 Zürich',
            'Wahlen15 Zug',
            'Wahlfahrt',
            'Wahlkampf',
            'Wahlserien',
            'Warnungen',
            'Warten auf Asyl',
            'Warum soll ich mir das antun? ',
            'We, Myself & Why',
            'Website und Apps',
            'WEF 2013',
            'WEF 2014',
            'WEF 2015',
            'WEF 2016',
            'WEF Interviews ',
            'Weitere Beiträge',
            'Weitere Rubriken und Serien',
            'Weiteres',
            'Welt im Wandel 1',
            'Welt im Wandel',
            'Weltbewegende Geschenke',
            'Weltcup Frauen',
            'Weltcup Männer',
            'Welten des Islam',
            'Weltklasse - Die Kritikerrunde',
            'Weltklasse auf SRF 2 Kultur',
            'Weltklasse – Sommerkonzerte',
            'Weltraum',
            'Werbung und Sponsoring',
            'Wettbewerb',
            'Wettbewerbsfilme',
            'Wetterbox',
            'Wettkampfstätten',
            'Wilder',
            'Winterferien',
            'Wintersport',
            'Wir sind die Schweiz',
            'Wir werden über 100',
            'Wirtschaft',
            'Wirtschaft, Politik',
            'Wissen tanken',
            'Wissen',
            'Wissens-Chats',
            'Wissenschaft im Gespräch',
            'Wissenschaftsmagazin ',
            'WM',
            'WM-Qualifikation',
            'Wochenende Film',
            'Wochenende Gesellschaft',
            'Wochenende Kunst',
            'Wochenende Literatur',
            'Wochenende Musik',
            'Wochenende Wissen',
            'Wochengast',
            'WochenRundShow',
            'Wochenthema',
            'Wohnen',
            'Wolfgang Wettstein',
            'World Music Special',
            'World Web Forum',
            'Wortkunst',
            'WortSchatz',
            'WSIMDA',
            'WTA-Tour',
            'Wunderland',
            'Wunschkonzert',
            'Yesterday When I Was Young',
            'Zürich - Malaga Retour',
            'Zürich Openair',
            'Zürich Schaffhausen',
            'Zürich',
            'Zürich-West',
            'Zambo-Bus Podcast',
            'Zambo: Tschanz mit allem',
            'Zamboskop',
            'Zentralschweiz',
            'Zersiedelungs-Initiative',
            'Zeugen der Zeit',
            'Ziit isch Gäld',
            'Ziit vertuble',
            'Zivilcourage',
            'Zmitz im Läbe',
            'Zoogä-n-am Boogä',
            'Zuccolini: «Überlegged si mal»',
            'Zukunftstag',
            'Zum Glück ist Freitag',
            'Zur aktuellen Sendung',
            'Zur Sendung',
            'Zurich Film Festival',
            'ZwanzigZwanzig',
            'Zwei am Morge',
            'Zwischen den Schlagzeilen',
            'Zwischenhalt',
            'Zytlupe',
        ];
    }
}
